### ISSUE TITLE
jQuery, leaflet und bootstrap einbinden (vom eigenen Server, minifiziert)

### ISSUE THREAD

**Issue by PaulaScharf** [PaulaScharf/GeoSoftware1-FinalProject#3]
entscheiden, ob wir leaflet-draw und oder leaflet-routing-machine verwenden

**Comment by PaulaScharf** [comment]
was ist popper?

**Comment by KPoppi** [comment]
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.

**Comment by PaulaScharf** [comment]
mittlerweile sind jquery und leaflet erfolgreich eingebunden, aber bootstrap wirft noch fehler aus...
